- 위도와 경도를 좌표로 생각한다.
- 두 좌표의 거리가 가장 가까운 지역의 날씨 정보에 영향을 받는다.
- x = Latitude, y = Longitude
- distance = sqrt((x_1 - x_2)^2 + (y_1-y_2)^2)

# Environment

In [1]:
import numpy as np
import pandas as pd
import os
import glob

In [2]:
path = os.getcwd()
path = path + '/' + "META"
csv_files = glob.glob(os.path.join(path, "*.csv"))
  
for f in csv_files:
    df = pd.read_csv(f)
      
    print('Location:', f)
    print('File Name:', f.split("\\")[-1])
      
    print('Content:')
    display(df)
    print()

Location: c:\Users\pc\OneDrive\Desktop\미세먼지 예측/META\awsmap.csv
File Name: awsmap.csv
Content:

   Location  Latitude  Longitude                           Description
0       오월드   36.2913   127.3959          대전광역시 중구사정공원로 70 오월드 내 플라워랜드
1        세천   36.3402   127.4938                    대전광역시 동구세천동 63-1
2        장동   36.4135   127.4382                   대전광역시 대덕구장동 360-2
3      세종고운   36.5315   127.2406                   세종특별자치시 고운동산 25번지
4      세종금남   36.4585   127.2688               세종특별자치시 시군구금남면 성덕리 77-3
5      세종연서   36.5667   127.2806                세종특별자치시 연서면봉암리 196-1
6      세종전의   36.6908   127.2005      세종특별자치시 전의면읍내리 5-1번지(전의생활체육공원)
7     북격렬비도   36.6254   125.5595          충청남도 태안군근흥면 가의도리산 27(북격렬비도)
8        호도   36.3012   126.2663                 충청남도 보령시오천면 녹도리 388-5
9        대산   37.0106   126.3881  충청남도 서산시대산읍 대죽리산95-1 (5304부대 대산방공진지)
10       홍북   36.6277   126.6451       충청남도 홍성군홍북면 상하리산91(1789부대 4대대)
11     홍성죽도   36.5200   126.4424                  충청남도 홍성군서부면 죽도리 33-1
12       공주   36.4828   127.1365         충청남도 공주시금흥동 산 21번지(공주예비군 훈련장)
13       서천   36.0625   126.7041         충청남도 서천군마서면 계동리 76-1서천군농업기술센터
14       논산   36.2116   127.1082                   충청남도 논산시덕지동 43-29
15       당진   36.8894   126.6174          충청남도 당진시채운동 363-23(당진예비군훈련장)
16       성거   36.8782   127.1561          충청남도 천안시서북구 성거읍봉주로 75(서북구청)
17       청양   36.4237   126.7791      충청남도 청양군청양읍 구봉로1026-84 청양농업기술센터
18       태안   36.7585   126.2964           충청남도 태안군태안읍 백화로49(태안초등학교)
19       예산   36.7421   126.8144       충청남도 예산군신암면 오신로852(예산군농업기술센터)
20       유구   36.5407   126.9336                충청남도 공주시유구읍 만천리500번지
21       정안   36.5511   127.0938                충청남도 공주시정안면 평정리284-5
22       아산   36.8458   126.8654     충청남도 아산시인주면 현대로1077(현대자동차㈜ 아산공장)
23       양화   36.1319   126.8602           충청남도 부여군양화면 충절로267-6 양화중학교
24       계룡   36.3132   127.2407       충청남도 계룡시신도안면 사서함 501-328호 공군기상단
25      춘장대   36.1741   126.5285                충청남도 서천군 서면 부사로 289부사교
26      대천항   36.3244   126.5021             충청남도 보령시신흑동 산 205155레이더기지
27       안도   36.9587   126.1683               충청남도 태안군원북면 방갈리산240번지
28       옹도   36.6476   126.0093                 충청남도 태안군근흥면 가의도리 산510
29       정산   36.3862   126.9565         충청남도 청양군정산면 학암리 19-2(축산기술연구소)

Location: c:\Users\pc\OneDrive\Desktop\미세먼지 예측/META\pmmap.csv
File Name: pmmap.csv
Content:

,Location,Latitude,Longitude,Description
0,아름동,36.512252,127.246789,세종특별자치시 보듬3로 114 아름동커뮤니티센터 옥상 (아름동)
1,신흥동,36.592887,127.292550,세종 조치원읍 군청로 87-16(신흥동) 세종특별자치시 조치원청사 옥상
2,노은동,36.368242,127.318498,대전 유성구 노은동로 87번길 89(노은1동 주민센터) 노은1동 주민센터 3층 옥상
3,문창동,36.317215,127.437825,대전 중구 보문로 20번길 38(문창동 주민센터) 문창동 주민센터
4,읍내동,36.372388,127.417714,대전 대덕구 대전로 1331번길 75(태아산업(주)) 태아산업(주)
5,정림동,36.304442,127.366742,대전 서구 정림동로 10(정림동 주민센터) 정림동 주민센터
6,공주,36.446951,127.119209,충남 공주시 봉황로 1 (공주시의회 옥상)
7,논산,36.199217,127.087021,충남 논산시 시민로 389 (취암/부창동 행정복지센터 2층 옥상)
8,대천2동,36.353148,126.589735,충남 보령시 중앙로 142-16 (대천2동 주민센터 옥상)
9,독곶리,36.987579,126.391672,충남 서산시 대산읍 평신1로(독곶리) 한국수자원공사 대산산업용수센터 저수동 옥상
10,동문동,36.780158,126.455197,충청남도 서산시 중앙로 38-1 서산초등학교 (동문동)
11,모종동,36.782700,127.014610,충남 아산시 모종동 573-2 보건소옥상
12,신방동,36.782355,127.120506,충남 천안시 동남구 천안천변길 127 천안시 맑은물사업소 하수처리장 (신방동)
13,예산군,36.677398,126.848918,충남 예산군 예산읍 신흥길 63 (다목적 노인회관 옥상)
14,이원면,36.869719,126.280501,충남 태안군 이원면 분지길 14 (이원면사무소 1층 나동 옥상)
15,홍성읍,36.597673,126.655087,충남 홍성군 홍성읍 내포로 136번길 29 (느티나무 어린이집 옥상)
16,성성동,36.840313,127.141777,충남 천안시 서북구 성성동 1-70

In [2]:
awsmap = pd.read_csv('META/awsmap.csv')
pmmap = pd.read_csv('META/pmmap.csv')

aws_lat = np.array(awsmap['Latitude']) # 위도 
aws_long = np.array(awsmap['Longitude']) # 경도 
aws_loc = np.array(awsmap['Location']) # 탐지소 지역명

In [5]:
distance_lat = list()
distance_long = list()
for index, row in pmmap.iterrows():
    distance_lat.append(aws_lat - row[1])
    distance_long.append(aws_long - row[2])
distance_lat = np.array(distance_lat)
distnace_long = np.array(distance_long)

distance = np.sqrt(np.square(distance_lat) + np.square(distance_long))

# 가장 가까운 거리
min_loc = list()
for d in distance:
    min_loc.append(np.argmin(d))

# 그곳의 이름
loc_match = dict()
for index, row in pmmap.iterrows():
    loc_match[row[0]] = aws_loc[min_loc[index]]
    
# 가나다순 정리
loc_match = dict(sorted(loc_match.items()))

In [9]:
loc_match

{'공주': '공주',
 '노은동': '계룡',
 '논산': '논산',
 '대천2동': '대천항',
 '독곶리': '대산',
 '동문동': '태안',
 '모종동': '아산',
 '문창동': '오월드',
 '성성동': '성거',
 '신방동': '성거',
 '신흥동': '세종연서',
 '아름동': '세종고운',
 '예산군': '예산',
 '읍내동': '장동',
 '이원면': '태안',
 '정림동': '오월드',
 '홍성읍': '홍북'}

In [10]:
# 저장
import pickle
with open('loc_match.pkl', 'wb') as f:
    pickle.dump(loc_match, f)

In [2]:
df = pd.read_csv('TEST_INPUT/공주.csv')
df[0:24*2]

    연도           일시 측정소  PM2.5
0    4  01-01 00:00  공주  0.060
1    4  01-01 01:00  공주  0.064
2    4  01-01 02:00  공주  0.072
3    4  01-01 03:00  공주  0.064
4    4  01-01 04:00  공주  0.056
5    4  01-01 05:00  공주  0.076
6    4  01-01 06:00  공주  0.060
7    4  01-01 07:00  공주  0.108
8    4  01-01 08:00  공주  0.084
9    4  01-01 09:00  공주  0.100
10   4  01-01 10:00  공주  0.080
11   4  01-01 11:00  공주  0.068
12   4  01-01 12:00  공주  0.068
13   4  01-01 13:00  공주  0.056
14   4  01-01 14:00  공주  0.060
15   4  01-01 15:00  공주  0.056
16   4  01-01 16:00  공주  0.056
17   4  01-01 17:00  공주  0.056
18   4  01-01 18:00  공주  0.052
19   4  01-01 19:00  공주  0.048
20   4  01-01 20:00  공주  0.068
21   4  01-01 21:00  공주  0.072
22   4  01-01 22:00  공주  0.068
23   4  01-01 23:00  공주  0.064
24   4  01-02 00:00  공주  0.064
25   4  01-02 01:00  공주  0.072
26   4  01-02 02:00  공주  0.072
27   4  01-02 03:00  공주  0.068
28   4  01-02 04:00  공주  0.068
29   4  01-02 05:00  공주  0.092
30   4  01-02 06:00  공주  0.092
31   4  01-02 07:00  공주  0.092
32   4  01-02 08:00  공주  0.112
33   4  01-02 09:00  공주  0.108
34   4  01-02 10:00  공주  0.048
35   4  01-02 11:00  공주  0.060
36   4  01-02 12:00  공주  0.044
37   4  01-02 13:00  공주  0.056
38   4  01-02 14:00  공주  0.048
39   4  01-02 15:00  공주  0.040
40   4  01-02 16:00  공주  0.044
41   4  01-02 17:00  공주  0.040
42   4  01-02 18:00  공주  0.040
43   4  01-02 19:00  공주  0.036
44   4  01-02 20:00  공주  0.044
45   4  01-02 21:00  공주  0.040
46   4  01-02 22:00  공주  0.052
47   4  01-02 23:00  공주  0.060

In [3]:
df[24*2:24*5]

     연도           일시 측정소  PM2.5
48    4  01-03 00:00  공주    NaN
49    4  01-03 01:00  공주    NaN
50    4  01-03 02:00  공주    NaN
51    4  01-03 03:00  공주    NaN
52    4  01-03 04:00  공주    NaN
..   ..          ...  ..    ...
115   4  01-05 19:00  공주    NaN
116   4  01-05 20:00  공주    NaN
117   4  01-05 21:00  공주    NaN
118   4  01-05 22:00  공주    NaN
119   4  01-05 23:00  공주    NaN

[72 rows x 4 columns]